//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nomina_2026_NET8.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RutaSeleccionada {
            get {
                return ((string)(this["RutaSeleccionada"]));
            }
            set {
                this["RutaSeleccionada"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RutaSalidaJSON {
            get {
                return ((string)(this["RutaSalidaJSON"]));
            }
            set {
                this["RutaSalidaJSON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*.NOM")]
        public string MostrarFiltroArchivos {
            get {
                return ((string)(this["MostrarFiltroArchivos"]));
            }
            set {
                this["MostrarFiltroArchivos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ryOnOCufik8ErhIKsR13Gr3nx01QsRHa3QzFWyFsLm0=")]
        public string AesKey {
            get {
                return ((string)(this["AesKey"]));
            }
            set {
                this["AesKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\ProgramData\\NominaEmpresarial2026\\Tarifas\\TablasTarifa.dat")]
        public string RutaTablasTarifa {
            get {
                return ((string)(this["RutaTablasTarifa"]));
            }
            set {
                this["RutaTablasTarifa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SQL6012.site4now.net;Initial Catalog=db_a4091b_sacmag;User ID=db_a409" +
            "1b_sacmag_admin;Password=Sacmag2020;Connect Timeout=10;")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
            set {
                this["ConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Rev$1597")]
        public string EditPassword {
            get {
                return ((string)(this["EditPassword"]));
            }
        }
    }
}
